name: Deploy to Test PyPi

on: 
  push:
      branches:
        - release_candidates
jobs:

  build_and_deploy:
   name: Build the release and deploy to test pypi
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Set up Python 3.11
     uses: actions/setup-python@v5
     with:
       python-version: 3.11

   - name: Install package
     run: |
       python -m pip install --upgrade pip
       pip install twine
       pip install build
       pip install . -U

   - name: List installed packages
     run: |
       pip show pymrio 
       pip list

   - name: Build and check packages
     run: |
       python -m build
       twine check --strict dist/*

   - name: Publish to TestPyPI
     env:
       TWINE_USERNAME: __token__
       TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
     run: python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*

