name: Deploy to PyPi

on: 
  release:
      types: [created]

jobs:
  build:
    name: Build the release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install package
        run: |
          pip install . -U
          python setup.py sdist
      - name: Upload
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYMRIO_PYPI_PW }}
